# Generated by Django 5.0.6 on 2024-05-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro_text',
            field=models.CharField(default='Stay curious, stay inspired, and let’s dive into the world of words together!', max_length=120),
        ),
    ]
